
INSERT INTO USER (USERNAME, PASSWORD, ENABLED, LASTPASSWORDRESETDATE) VALUES ('test', '5f4dcc3b5aa765d61d8327deb882cf99', 1, PARSEDATETIME('01-01-2018', 'dd-MM-yyyy'));
INSERT INTO USER (USERNAME, PASSWORD, ENABLED, LASTPASSWORDRESETDATE) VALUES ('test1', '5f4dcc3b5aa765d61d8327deb882cf99', 1, PARSEDATETIME('01-01-2018', 'dd-MM-yyyy'));

INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);

INSERT INTO MESSAGE (CREATED, FROM_USER_ID, TEXT, CONVERSATION_ID, IN_CHAT_ROOM) VALUES (PARSEDATETIME('01-01-2018', 'dd-MM-yyyy'), 1, 'Hello, world!', 1, 1);
INSERT INTO MESSAGE (CREATED, FROM_USER_ID, TEXT, CONVERSATION_ID, IN_CHAT_ROOM) VALUES (PARSEDATETIME('01-01-2018', 'dd-MM-yyyy'), 2, 'Hi, world!', 1, 1);

INSERT INTO CONVERSATION (NAME, PARTICIPANT1, PARTICIPANT2) VALUES ('chat-room', 1, 2);
INSERT INTO CONVERSATION (NAME, PARTICIPANT1, PARTICIPANT2) VALUES ('test-test1', 1, 2);
